# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='FIRSTNAME',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='LASTNAME',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='MIDLLENAME',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CITY',
            field=models.CharField(max_length=100, verbose_name='City:'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='EMAIL',
            field=models.EmailField(max_length=100, verbose_name='Email Address:'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='NUMBER',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PHONE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SSN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='STATE',
            field=models.CharField(max_length=2, verbose_name='State:'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='STREET',
            field=models.CharField(max_length=100, verbose_name='Street:'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ZIP',
            field=models.IntegerField(),
        ),
    ]
