# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NUMBER',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PHONE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SSN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ZIP',
            field=models.IntegerField(),
        ),
    ]
